### ISSUE TITLE
Question about trace mode when I run main.py

### ISSUE THREAD

**Issue by cbyan1003** [ShunChengWu/3DSSG#30]
Hello, i am a student from xi.an. 
When I run main.py on pre-trained config, I met these errors:
` python main.py --mode trace --config ./CVPR21/config_CVPR21.json`
`Traceback (most recent call last):
  File "main.py", line 6, in <module>
    from src.SceneGraphFusionNetwork import SGFN
  File "/home/bobo/project/3DSSG/src/SceneGraphFusionNetwork.py", line 6, in <module>
    from model_SGFN import SGFNModel
  File "./src/model_SGFN.py", line 11, in <module>
    from network_PointNet import PointNetfeat,PointNetCls,PointNetRelCls,PointNetRelClsMulti
  File "./src/network_PointNet.py", line 17, in <module>
    import op_utils
  File "./src/op_utils.py", line 7, in <module>
    from torch_geometric.nn.conv import MessagePassing
  File "/home/bobo/anaconda3/envs/SceneGraphFusion/lib/python3.8/site-packages/torch_geometric/__init__.py", line 5, in <module>
    import torch_geometric.data
  File "/home/bobo/anaconda3/envs/SceneGraphFusion/lib/python3.8/site-packages/torch_geometric/data/__init__.py", line 1, in <module>
    from .data import Data
  File "/home/bobo/anaconda3/envs/SceneGraphFusion/lib/python3.8/site-packages/torch_geometric/data/data.py", line 8, in <module>
    from torch_sparse import coalesce, SparseTensor
  File "/home/bobo/anaconda3/envs/SceneGraphFusion/lib/python3.8/site-packages/torch_sparse/__init__.py", line 14, in <module>
    torch.ops.load_library(importlib.machinery.PathFinder().find_spec(
AttributeError: 'NoneType' object has no attribute 'origin'`
Would you please tell me how to find where is wrong. (I followed the steps in README.txt of 3DSSG and I have downloaded and unzipped the pre-trained model "CVPR21")
I would appreciate it if you could reply.

**Comment by ShunChengWu** [comment]
I am not sure... can you format your text better?
I guess it's related to Pytorch.
